bot_token: "6674995287:AAGK820XcZiKkzYEBK_jRaFMk0eImWX97-c"
webhook_url: "https://weather.siky.me:8443/webhook"
cert_file_path: "/etc/letsencrypt/live/weather.siky.me/fullchain.pem"
key_file_path: "/etc/letsencrypt/live/weather.siky.me/privkey.pem"